apiVersion: v1
kind: Service
metadata:
  name: app-mbsd-nodeport-service
  namespace: platform-engineer
  labels:
    app: app-mbsd
spec:
  type: NodePort
  selector:
    app: app-mbsd
  ports:
    - port: 8080
      targetPort:  8080
